name: Test proyecto
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: coge mi codigo del repositorio
        uses: actions/checkout@v3
      - name: instalar nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: instalar dependencias
        run: npm ci
      - name: ejecutar los test
        run: npm test